# Generated by Django 2.0.7 on 2019-09-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('product_description', models.TextField(blank=True, max_length=500, null=True)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=100000, null=True)),
            ],
        ),
    ]
